### PR TITLE
[WIP] Update dependencies

### PR DESCRIPTION
**Pull request by mrk-j**
Hi,

We were using this package but it wasn't working anymore since at least PHP 8.1, I took the liberty updating the dependencies.

Let me know if there are any issues and/or if you want to merge this.

Thank you 😄

### CODE REVIEW

**Comment by freekmurze** [comment]
Very nice, could you also make the tests / style checks run on GitHub actions?

You can copy some stuff from our packages: https://github.com/spatie/laravel-backup/tree/main/.github/workflows

**Comment by mrk-j** [comment]
I will look into this in the coming days.

**Comment by bbashy** [comment]
Would be good to have this on php 8.1

**Comment by mrk-j** [comment]
I _think_ everything must be in order now. As far as I can see at least the PHP CS Fixer has ran. I'm not entirely sure if all is OK now. Can you check?

**Comment by freekmurze** [comment]
Seems ok when quickly glancing over the code. 

Did you test out the CLI tool itself? Is it working?

**Comment by mrk-j** [comment]
It is:
```
➜  mixed-content-scanner-cli git:(update-dependencies) ✗ ./mixed-content-scanner scan https://spatie.be


Start scanning https://spatie.be for mixed content
==================================================

https://spatie.be/: ok
https://spatie.be/vacancies: ok
https://spatie.be/products: ok
https://spatie.be/web-development: ok
https://spatie.be/about-us: ok
https://spatie.be/guidelines: ok
https://spatie.be/blog: ok
https://spatie.be/docs: ok
https://spatie.be/login: ok
[...]

➜  mixed-content-scanner-cli git:(update-dependencies) ✗ ./mixed-content-scanner scan https://www.mixedcontentexamples.com/Test/NonSecureImage


Start scanning https://www.mixedcontentexamples.com/Test/NonSecureImage for mixed content
=========================================================================================

https://www.mixedcontentexamples.com/Test/NonSecureImage: found mixed content on element img with url http://www.mixedcontentexamples.com/Content/Test/steveholt.jpg

Scan results
============

Found 1 pieces of mixed content
 * https://www.mixedcontentexamples.com/Test/NonSecureImage: found mixed content on element img with url http://www.mixedcontentexamples.com/Content/Test/steveholt.jpg

Found 0 pages without mixed content
```

**Comment by freekmurze** [comment]
Thank you for your work on this!

**Pull request merged**
